import pandas as pd


def total_revenue(df):
    """
    Calculate total revenue.
    """
    return round(df["Revenue"].sum(), 2)


def total_profit(df):
    """
    Calculate total profit.
    """
    return round(df["Profit"].sum(), 2)


def total_orders(df):
    """
    Calculate total number of orders.
    """
    return len(df)


def average_order_value(df):
    """
    Calculate average revenue per order.
    """
    return round(df["Revenue"].mean(), 2)


def revenue_by_country(df):
    """
    Revenue generated by each country.
    """
    country = (
        df.groupby("Country")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    return country


def profit_by_country(df):
    """
    Profit generated by each country.
    """
    country = (
        df.groupby("Country")["Profit"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    return country


def monthly_revenue(df):
    """
    Monthly revenue trend.
    """
    monthly = (
        df.groupby("Order_Month")["Revenue"]
        .sum()
        .reset_index()
        .sort_values("Order_Month")
    )

    return monthly


def monthly_profit(df):
    """
    Monthly profit trend.
    """
    monthly = (
        df.groupby("Order_Month")["Profit"]
        .sum()
        .reset_index()
        .sort_values("Order_Month")
    )

    return monthly


def revenue_by_category(df):
    """
    Revenue by product category.
    """
    category = (
        df.groupby("Category")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    return category


def top_selling_products(df, n=10):
    """
    Top products based on revenue.
    """
    products = (
        df.groupby("Product_Name")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .head(n)
        .reset_index()
    )

    return products


def orders_by_country(df):
    """
    Number of orders by country.
    """
    orders = (
        df.groupby("Country")
        .size()
        .reset_index(name="Orders")
        .sort_values(
            by="Orders",
            ascending=False
        )
    )

    return orders


def profit_margin(df):
    """
    Overall profit margin percentage.
    """
    revenue = df["Revenue"].sum()
    profit = df["Profit"].sum()

    if revenue == 0:
        return 0

    return round((profit / revenue) * 100, 2)